version: '3.7'
services:
  api:
    image: gcr.io/red-seeker-356107/api:latest
    environment:
      - NODE_ENV=production
    env_file:
      - ./config/.env
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./uploads:/nemo/uploads

