version: '3.7'
services:
  db:
    image: mysql
    # volumes:
      # - /opt/lib/mysql:/var/lib/mysql
    env_file:
      - ./config/.env
    ports:
      - 5342:3306

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./config/.env
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./uploads:/nemo/uploads
      - ./config:/nemo/config
      - ./app.js:/nemo/app.js
      - ./services:/nemo/services
      - ./controllers:/nemo/controllers
    depends_on:
      - db
