name: main PR

on:
  pull_request:
    branches: [ "main" ]

env:
  TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
  TEST_TEST_ROOT_PASSWORD: ${{ secrets.TEST_TEST_ROOT_PASSWORD }}
  TEST_HOST: ${{ secrets.TEST_HOST }}
  TEST_PORT: ${{ secrets.TEST_PORT }}
  TEST_DATABASE: ${{ secrets.TEST_DATABASE }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/gallium'
    - name: install dependencies
      run:  npm i

    - name: run test
      run: npm run test
