name: CI

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: GCP auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build Image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:$GITHUB_SHA .

      # Configure docker to use the gcloud command-line tool as a credential helper

      - name: docker config
        run: gcloud auth configure-docker -q

      # Push image to Google Container Registry
      - name: Push Image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:$GITHUB_SHA

      # - name: 'Use gcloud CLI'
      #   run: gcloud compute ssh --project=${{secrets.GCP_PROJECT_ID}} --zone=${{ secrets.GCP_REGION }} ${{ secrets.GCP_VM_NAME }}

      # - name: 'pull image'
      #   run: 'docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:$GITHUB_SHA'

