# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: GCP auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build Image
        run: docker build \
            -e MYSQL_HOST=${{secrets.MYSQL_HOST}} \
            -e MYSQL_PORT=${{secrets.MYSQL_PORT}} \
            -e MYSQL_ROOT_PASSWORD=${{secrets.MYSQL_ROOT_PASSWORD}} \
            -e MYSQL_USERNAME=${{secrets.MYSQL_USERNAME}} \
            -e MYSQL_DATABASE=${{secrets.MYSQL_DATABASE}} \
            -e GCS_PROJECT_ID=${{secrets.PROJECT_ID}} \
            -e GCS_BUCKET_NAME=${{secrets.BUCKET_NAME}} \
            -e GCS_GCS_IMAGE_PREFIX=${{secrets.GCS_IMAGE_PREFIX}} \
            -e GCS_PRIVATE_KEY=${{secrets.GCS_PRIVATE_KEY}}
            -e GCP_PROJECT_ID=${{secrets.GCP_PROJECT_ID}} \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:latest .

      # Configure docker to use the gcloud command-line tool as a credential helper

      - name: docker config
        run: gcloud auth configure-docker -q

      # Push image to Google Container Registry
      - name: Push Image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:latest


